# Generated by Django 4.2.3 on 2023-08-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadesmd', '0001_initial'),
        ('matriz_dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrizdispositivos',
            unique_together={('cod_as400', 'unidad_medica', 'version')},
        ),
    ]
